---
title: "Solution to Exercise 2"
header-includes: |
  \usepackage{fancyhdr}
  \usepackage{datetime}
  \newdateformat{mydate}{\the\day.\the\month.\the\year}
  \pagestyle{fancy}
  \renewcommand{\headrulewidth}{0pt}
  \fancyhead[L]{\empty}
  \fancyhead[R]{\thepage}
  \fancyfoot[C]{
    \begin{tabular}[b]{c}%
      \small R: Basic Introduction, University of Zurich | \mydate\today\ \\
      \small by Simon Knüsel, r\_courses(at)gmx.ch \\
    \end{tabular}
  }
output:
  pdf_document: default
  html_document:
    number_sections: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Vectors

### 1. Create vectors
```{r create vec1}
vec1 <- seq(from = 1, to = 10, by = 0.5)
vec1
```
<br>
```{r create vec2}
vec2 <- rep(c(1, 4, 8, 13), each = 4)
vec2
```
<br><br>

### 2. Combine vectors
Combine the vectors `canton` and `peak` to `peak_canton`.

```{r create canton and peak and peak_canton}
# Create the vectors canton and peak
canton <- c("GR", "TI", "UR", "BE", "VS")
peak <- c("Piz Bernina", "Adula Rheinwaldhorn", "Dammastock", 
          "Finsteraarhorn", "Dufourspitze")

# Combine the vectors to peak_canton
peak_canton <- paste(peak, canton, sep = "_")
peak_canton
```
