---
title: "Solution to Exercise 1"
header-includes: |
  \usepackage{fancyhdr}
  \usepackage{datetime}
  \newdateformat{mydate}{\the\day.\the\month.\the\year}
  \pagestyle{fancy}
  \renewcommand{\headrulewidth}{0pt}
  \fancyhead[L]{\empty}
  \fancyhead[R]{\thepage}
  \fancyfoot[C]{
    \begin{tabular}[b]{c}%
      \small R: Basic Introduction, University of Zurich | \mydate\today\ \\
      \small by Simon Knüsel, simon.knuesel(at)wsl.ch \\
    \end{tabular}
  }
output:
  pdf_document: default
  html_document:
    number_sections: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
<br>

### 1. What results do you expect of the following commands?
```{r guess results solution, echo = TRUE}
x <- c(2, 5, 6, 5)
y <- c(3, 5, 8)

class(x)

x + 1
x + y
y * 2

y[2:3]
x[x > 5]
x[1:3] + y

x <- x[1:2]
length(x)
```


```{r pagebreak #1, results="asis", echo = FALSE}
if ("pdf_document" %in% rmarkdown::all_output_formats(knitr::current_input())) {
  cat("\\pagebreak")
}
```


### 2. Create vectors
```{r create vec1, echo = TRUE}
vec1 <- seq(from = 1, to = 10, by = 0.5)
vec1
```
<br>
```{r create vec2, echo = TRUE}
vec2 <- rep(c(1, 4, 8, 13), each = 4)
vec2
```
<br><br>

### 3. Combine vectors
Combine the vectors `canton` and `peak` to `peak_canton`.

```{r create canton and peak and peak_canton, echo = TRUE}
canton <- c("GR", "TI", "UR", "BE", "VS")
peak <- c("Piz Bernina", "Adula Rheinwaldhorn", "Dammastock", 
          "Finsteraarhorn", "Dufourspitze")

peak_canton <- paste(peak, canton, sep = "_")
peak_canton
```


```{r pagebreak #2, results="asis", echo = FALSE}
if ("pdf_document" %in% rmarkdown::all_output_formats(knitr::current_input())) {
  cat("\\pagebreak")
}
```


### 4. Load and save a .csv-file

```{r set working directory, include=FALSE}
knitr::opts_knit$set(root.dir = "/Users/simonknusel/Documents/02_Job/06_PostDoc/06_R-Courses/01_UZH_courses/2019/R_Basic_Introduction/")
```

i) Load the file `tree_growth_data.csv` from the folder `01_Data` and give 
it a name (e.g. `my_table`)

```{r getwd, echo = TRUE, eval = FALSE, results = "hide", warning=FALSE, error=FALSE}
# Set your working directory to the folder 'R_Basic_Introduction'
setwd("insert_path_to_folder_R_Basic_Introduction")
```

```{r load .csv-file, echo = TRUE}
my_table <- read.csv(file = "01_Data/tree_growth_data.csv")

head(my_table)
```
<br><br>

ii) Save the object `my_table` as `my_table.csv` to the folder `01_Data`

```{r write my_table to file, echo = TRUE}
write.csv(my_table, file = "01_Data/my_table.csv")
```

